version: '3'
services:
  xrayr:
    container_name: yaoyue
    image: crackair/xrayr:latest
    volumes:
      - ./config/:/etc/XrayR/ # 映射配置文件夹
    restart: always
    network_mode: host
    logging:
      options:
        max-size: 300m